[tool.poetry]
name = "gitlab-ui"
version = "0.1.0"
description = ""
authors = ["Vladimir Puzakov <vppuzakov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
npyscreen = "^4.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
